---
- name: Setup database
  hosts: db
  become: true
  tasks:
    - name: Run database playbook
      include_role:
        name: db

- name: Setup web server
  hosts: server
  become: true
  tasks:
    - name: Run web server playbook
      include_role:
        name: server
